# -*- coding: utf-8 -*-
"""SVM

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qXb48QxlnOy4re9jxUCRZcHfNzB7N1CR
"""

# import pandas as pd
# from sklearn import svm
# from sklearn.model_selection import train_test_split
# from sklearn.metrics import accuracy_score
# from sklearn.model_selection import train_test_split
# from sklearn.preprocessing import OneHotEncoder
# from sklearn.compose import ColumnTransformer
# from sklearn.pipeline import Pipeline

# # Load data from CSV
# data = pd.read_csv('data_classification_training.csv')
# # data["duration"] = pd.to_datetime(data["duration"])
# data["hour"] =  pd.to_datetime(data['duration']).dt.hour
# data["weekday"] = pd.to_datetime(data['duration']).dt.weekday

# # Assuming 'amount', 'date', and 'vpa' are the features, and 'label' is the target variable
# X = data[['amount', 'hour','weekday', 'vpa']]
# y = data['label']

# preprocessor = ColumnTransformer(
#     transformers=[
#         ('onehot', OneHotEncoder(), ['vpa'])
#     ])

# # Combine preprocessing with the classifier
# clf = Pipeline(steps=[('preprocessor', preprocessor),
#                       ('classifier', svm.SVC(kernel='linear'))])


# # Split data into training and testing sets
# X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# # Initialize SVM classifier
# clf = svm.SVC(kernel='linear')

# # Train the classifier
# clf.fit(X_train, y_train)

# # Predict labels for new data
# new_data = pd.read_csv('new_data.csv')  # Load new data from CSV
# new_data["hour"] =  pd.to_datetime(new_data['duration']).dt.hour
# new_data["weekday"] = pd.to_datetime(new_data['duration']).dt.weekday
# X_new = new_data[['amount','hour','weekday', 'vpa']]
# predicted_labels = clf.predict(X_new)

# # Output predicted labels
# print("Predicted labels for new data:")
# print(predicted_labels)
